/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const CommentListId = IDL.Text;
export const CommentId = IDL.Text;
export const Principal = IDL.Principal;
export const AppEventId = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AiCommentId = IDL.Text;
export const MessageId = IDL.Text;
export const RatingImageId = IDL.Text;
export const Time = IDL.Int;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const RatingImageMetadata = IDL.Record({
  'id' : RatingImageId,
  'userName' : IDL.Text,
  'timestamp' : Time,
  'uploader' : Principal,
  'image' : ExternalBlob,
});
export const Comment = IDL.Record({
  'id' : CommentId,
  'content' : IDL.Text,
  'used' : IDL.Bool,
  'timestamp' : Time,
});
export const DeviceId = IDL.Text;
export const AIComment = IDL.Record({
  'id' : AiCommentId,
  'content' : IDL.Text,
  'ratingSymbol' : IDL.Text,
  'appLinkOrName' : IDL.Text,
  'timestamp' : Time,
});
export const AppEvent = IDL.Record({
  'id' : AppEventId,
  'name' : IDL.Text,
  'createdAt' : Time,
  'usernames' : IDL.Vec(IDL.Text),
});
export const MessageSide = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
});
export const Message = IDL.Record({
  'id' : MessageId,
  'content' : IDL.Text,
  'side' : MessageSide,
  'isRead' : IDL.Bool,
  'sender' : IDL.Opt(Principal),
  'timestamp' : Time,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const PaymentRecord = IDL.Record({
  'id' : IDL.Text,
  'status' : PaymentStatus,
  'userPrincipal' : Principal,
  'timestamp' : Time,
  'amount' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'upiDetails' : IDL.Text,
  'name' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func(
      [IDL.Text, CommentListId, CommentId, IDL.Text],
      [],
      [],
    ),
  'addFundsToWallet' : IDL.Func([IDL.Text, Principal, IDL.Nat], [], []),
  'addUsernameToAppEvent' : IDL.Func([IDL.Text, AppEventId, IDL.Text], [], []),
  'addUsernamesToAppEvent' : IDL.Func(
      [IDL.Text, AppEventId, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkUsernamesInAppEvent' : IDL.Func(
      [AppEventId, IDL.Vec(IDL.Text)],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool))],
      ['query'],
    ),
  'clearAllAiComments' : IDL.Func([IDL.Text], [], []),
  'clearAllCommentLists' : IDL.Func([IDL.Text], [], []),
  'clearEverything' : IDL.Func([IDL.Text], [], []),
  'createAiComment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [AiCommentId],
      [],
    ),
  'createAppEvent' : IDL.Func([IDL.Text, IDL.Text], [AppEventId], []),
  'createCommentList' : IDL.Func([IDL.Text, CommentListId], [], []),
  'deleteAiComment' : IDL.Func([IDL.Text, AiCommentId], [], []),
  'deleteAppEvent' : IDL.Func([IDL.Text, AppEventId], [], []),
  'deleteCommentList' : IDL.Func([IDL.Text, CommentListId], [], []),
  'deleteMessage' : IDL.Func([IDL.Text, MessageId], [], []),
  'downloadAllRatingImages' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(RatingImageMetadata)],
      ['query'],
    ),
  'generateBulkComments' : IDL.Func(
      [IDL.Text, CommentListId, IDL.Nat],
      [IDL.Vec(Comment)],
      [],
    ),
  'generateSingleComment' : IDL.Func(
      [CommentListId, DeviceId],
      [IDL.Opt(IDL.Text)],
      [],
    ),
  'getAiComment' : IDL.Func(
      [IDL.Text, AiCommentId],
      [IDL.Opt(AIComment)],
      ['query'],
    ),
  'getAllAiComments' : IDL.Func([IDL.Text], [IDL.Vec(AIComment)], ['query']),
  'getAllAppEvents' : IDL.Func([IDL.Text], [IDL.Vec(AppEvent)], ['query']),
  'getAllBulkCommentTotals' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(CommentListId, IDL.Nat))],
      ['query'],
    ),
  'getAllMessages' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
  'getAllPaymentRecords' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(Principal, IDL.Vec(PaymentRecord)))],
      ['query'],
    ),
  'getAllUserRatingImages' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(RatingImageMetadata)))],
      ['query'],
    ),
  'getAppEvent' : IDL.Func(
      [IDL.Text, AppEventId],
      [IDL.Opt(AppEvent)],
      ['query'],
    ),
  'getAppEventIds' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(AppEventId, IDL.Text))],
      ['query'],
    ),
  'getAvailableComments' : IDL.Func(
      [CommentListId],
      [IDL.Opt(IDL.Vec(Comment))],
      ['query'],
    ),
  'getBulkGeneratorKey' : IDL.Func(
      [IDL.Text, IDL.Bool],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommentList' : IDL.Func(
      [IDL.Text, CommentListId],
      [IDL.Vec(Comment)],
      ['query'],
    ),
  'getCommentListIds' : IDL.Func([], [IDL.Vec(CommentListId)], ['query']),
  'getCommentListTotal' : IDL.Func(
      [IDL.Text, CommentListId],
      [IDL.Nat],
      ['query'],
    ),
  'getDeviceSingleCommentHistory' : IDL.Func(
      [DeviceId],
      [IDL.Vec(IDL.Tuple(CommentListId, IDL.Bool))],
      ['query'],
    ),
  'getLockedCommentListIds' : IDL.Func([], [IDL.Vec(CommentListId)], ['query']),
  'getLockedCommentListsTotal' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getPaymentHistory' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
  'getRemainingCount' : IDL.Func([CommentListId], [IDL.Nat], ['query']),
  'getTotalUserRatingCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func([Principal], [IDL.Opt(UserProfile)], ['query']),
  'getUserRatingImageCount' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Nat],
      ['query'],
    ),
  'getWalletBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'hasSingleCommentGenerated' : IDL.Func(
      [DeviceId, CommentListId],
      [IDL.Bool],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCommentListLocked' : IDL.Func([CommentListId], [IDL.Bool], ['query']),
  'lockCommentList' : IDL.Func([IDL.Text, CommentListId], [], []),
  'removeAllUserRatingImages' : IDL.Func([IDL.Text], [], []),
  'removeComment' : IDL.Func([IDL.Text, CommentListId, CommentId], [], []),
  'removeRatingImage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'removeUsernameFromAppEvent' : IDL.Func(
      [IDL.Text, AppEventId, IDL.Text],
      [],
      [],
    ),
  'replyMessage' : IDL.Func([IDL.Text, IDL.Text], [MessageId], []),
  'resetAppEventUsernames' : IDL.Func([IDL.Text, AppEventId], [], []),
  'resetBulkGeneratorKey' : IDL.Func([IDL.Text], [], []),
  'resetCommentList' : IDL.Func([IDL.Text, CommentListId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Text], [MessageId], []),
  'setBulkGeneratorKey' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'unlockCommentList' : IDL.Func([IDL.Text, CommentListId], [], []),
  'updatePaymentStatus' : IDL.Func(
      [IDL.Text, Principal, IDL.Text, PaymentStatus],
      [],
      [],
    ),
  'uploadRatingImage' : IDL.Func(
      [IDL.Text, IDL.Text, ExternalBlob],
      [RatingImageId],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const CommentListId = IDL.Text;
  const CommentId = IDL.Text;
  const Principal = IDL.Principal;
  const AppEventId = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AiCommentId = IDL.Text;
  const MessageId = IDL.Text;
  const RatingImageId = IDL.Text;
  const Time = IDL.Int;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const RatingImageMetadata = IDL.Record({
    'id' : RatingImageId,
    'userName' : IDL.Text,
    'timestamp' : Time,
    'uploader' : Principal,
    'image' : ExternalBlob,
  });
  const Comment = IDL.Record({
    'id' : CommentId,
    'content' : IDL.Text,
    'used' : IDL.Bool,
    'timestamp' : Time,
  });
  const DeviceId = IDL.Text;
  const AIComment = IDL.Record({
    'id' : AiCommentId,
    'content' : IDL.Text,
    'ratingSymbol' : IDL.Text,
    'appLinkOrName' : IDL.Text,
    'timestamp' : Time,
  });
  const AppEvent = IDL.Record({
    'id' : AppEventId,
    'name' : IDL.Text,
    'createdAt' : Time,
    'usernames' : IDL.Vec(IDL.Text),
  });
  const MessageSide = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
  const Message = IDL.Record({
    'id' : MessageId,
    'content' : IDL.Text,
    'side' : MessageSide,
    'isRead' : IDL.Bool,
    'sender' : IDL.Opt(Principal),
    'timestamp' : Time,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const PaymentRecord = IDL.Record({
    'id' : IDL.Text,
    'status' : PaymentStatus,
    'userPrincipal' : Principal,
    'timestamp' : Time,
    'amount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'upiDetails' : IDL.Text,
    'name' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'email' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func(
        [IDL.Text, CommentListId, CommentId, IDL.Text],
        [],
        [],
      ),
    'addFundsToWallet' : IDL.Func([IDL.Text, Principal, IDL.Nat], [], []),
    'addUsernameToAppEvent' : IDL.Func(
        [IDL.Text, AppEventId, IDL.Text],
        [],
        [],
      ),
    'addUsernamesToAppEvent' : IDL.Func(
        [IDL.Text, AppEventId, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkUsernamesInAppEvent' : IDL.Func(
        [AppEventId, IDL.Vec(IDL.Text)],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool))],
        ['query'],
      ),
    'clearAllAiComments' : IDL.Func([IDL.Text], [], []),
    'clearAllCommentLists' : IDL.Func([IDL.Text], [], []),
    'clearEverything' : IDL.Func([IDL.Text], [], []),
    'createAiComment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [AiCommentId],
        [],
      ),
    'createAppEvent' : IDL.Func([IDL.Text, IDL.Text], [AppEventId], []),
    'createCommentList' : IDL.Func([IDL.Text, CommentListId], [], []),
    'deleteAiComment' : IDL.Func([IDL.Text, AiCommentId], [], []),
    'deleteAppEvent' : IDL.Func([IDL.Text, AppEventId], [], []),
    'deleteCommentList' : IDL.Func([IDL.Text, CommentListId], [], []),
    'deleteMessage' : IDL.Func([IDL.Text, MessageId], [], []),
    'downloadAllRatingImages' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(RatingImageMetadata)],
        ['query'],
      ),
    'generateBulkComments' : IDL.Func(
        [IDL.Text, CommentListId, IDL.Nat],
        [IDL.Vec(Comment)],
        [],
      ),
    'generateSingleComment' : IDL.Func(
        [CommentListId, DeviceId],
        [IDL.Opt(IDL.Text)],
        [],
      ),
    'getAiComment' : IDL.Func(
        [IDL.Text, AiCommentId],
        [IDL.Opt(AIComment)],
        ['query'],
      ),
    'getAllAiComments' : IDL.Func([IDL.Text], [IDL.Vec(AIComment)], ['query']),
    'getAllAppEvents' : IDL.Func([IDL.Text], [IDL.Vec(AppEvent)], ['query']),
    'getAllBulkCommentTotals' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(CommentListId, IDL.Nat))],
        ['query'],
      ),
    'getAllMessages' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
    'getAllPaymentRecords' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(Principal, IDL.Vec(PaymentRecord)))],
        ['query'],
      ),
    'getAllUserRatingImages' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(RatingImageMetadata)))],
        ['query'],
      ),
    'getAppEvent' : IDL.Func(
        [IDL.Text, AppEventId],
        [IDL.Opt(AppEvent)],
        ['query'],
      ),
    'getAppEventIds' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(AppEventId, IDL.Text))],
        ['query'],
      ),
    'getAvailableComments' : IDL.Func(
        [CommentListId],
        [IDL.Opt(IDL.Vec(Comment))],
        ['query'],
      ),
    'getBulkGeneratorKey' : IDL.Func(
        [IDL.Text, IDL.Bool],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommentList' : IDL.Func(
        [IDL.Text, CommentListId],
        [IDL.Vec(Comment)],
        ['query'],
      ),
    'getCommentListIds' : IDL.Func([], [IDL.Vec(CommentListId)], ['query']),
    'getCommentListTotal' : IDL.Func(
        [IDL.Text, CommentListId],
        [IDL.Nat],
        ['query'],
      ),
    'getDeviceSingleCommentHistory' : IDL.Func(
        [DeviceId],
        [IDL.Vec(IDL.Tuple(CommentListId, IDL.Bool))],
        ['query'],
      ),
    'getLockedCommentListIds' : IDL.Func(
        [],
        [IDL.Vec(CommentListId)],
        ['query'],
      ),
    'getLockedCommentListsTotal' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getPaymentHistory' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
    'getRemainingCount' : IDL.Func([CommentListId], [IDL.Nat], ['query']),
    'getTotalUserRatingCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func([Principal], [IDL.Opt(UserProfile)], ['query']),
    'getUserRatingImageCount' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Nat],
        ['query'],
      ),
    'getWalletBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'hasSingleCommentGenerated' : IDL.Func(
        [DeviceId, CommentListId],
        [IDL.Bool],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCommentListLocked' : IDL.Func([CommentListId], [IDL.Bool], ['query']),
    'lockCommentList' : IDL.Func([IDL.Text, CommentListId], [], []),
    'removeAllUserRatingImages' : IDL.Func([IDL.Text], [], []),
    'removeComment' : IDL.Func([IDL.Text, CommentListId, CommentId], [], []),
    'removeRatingImage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'removeUsernameFromAppEvent' : IDL.Func(
        [IDL.Text, AppEventId, IDL.Text],
        [],
        [],
      ),
    'replyMessage' : IDL.Func([IDL.Text, IDL.Text], [MessageId], []),
    'resetAppEventUsernames' : IDL.Func([IDL.Text, AppEventId], [], []),
    'resetBulkGeneratorKey' : IDL.Func([IDL.Text], [], []),
    'resetCommentList' : IDL.Func([IDL.Text, CommentListId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Text], [MessageId], []),
    'setBulkGeneratorKey' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'unlockCommentList' : IDL.Func([IDL.Text, CommentListId], [], []),
    'updatePaymentStatus' : IDL.Func(
        [IDL.Text, Principal, IDL.Text, PaymentStatus],
        [],
        [],
      ),
    'uploadRatingImage' : IDL.Func(
        [IDL.Text, IDL.Text, ExternalBlob],
        [RatingImageId],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };