/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const CommentListId = IDL.Text;
export const CommentId = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Comment = IDL.Record({
  'id' : CommentId,
  'content' : IDL.Text,
  'used' : IDL.Bool,
  'timestamp' : Time,
});
export const DeviceId = IDL.Text;
export const MessageId = IDL.Text;
export const MessageSide = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
});
export const Message = IDL.Record({
  'id' : MessageId,
  'content' : IDL.Text,
  'side' : MessageSide,
  'isRead' : IDL.Bool,
  'timestamp' : Time,
});
export const RatingImageId = IDL.Text;
export const Principal = IDL.Principal;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const RatingImageMetadata = IDL.Record({
  'id' : RatingImageId,
  'timestamp' : Time,
  'uploader' : Principal,
  'image' : ExternalBlob,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([CommentListId, CommentId, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearAllCommentLists' : IDL.Func([IDL.Text], [], []),
  'createCommentList' : IDL.Func([IDL.Text, CommentListId], [], []),
  'deleteCommentList' : IDL.Func([IDL.Text, CommentListId], [], []),
  'generateBulkComments' : IDL.Func(
      [IDL.Text, CommentListId, IDL.Nat],
      [IDL.Vec(Comment)],
      [],
    ),
  'generateComment' : IDL.Func(
      [CommentListId, DeviceId],
      [IDL.Opt(Comment)],
      [],
    ),
  'getAllBulkCommentTotals' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(CommentListId, IDL.Nat))],
      ['query'],
    ),
  'getAllMessages' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
  'getAllRatingImages' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(RatingImageMetadata)],
      ['query'],
    ),
  'getAvailableComments' : IDL.Func(
      [CommentListId],
      [IDL.Opt(IDL.Vec(Comment))],
      ['query'],
    ),
  'getBulkGeneratorKey' : IDL.Func(
      [IDL.Text, IDL.Bool],
      [IDL.Opt(IDL.Text)],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommentList' : IDL.Func(
      [IDL.Text, CommentListId],
      [IDL.Vec(Comment)],
      ['query'],
    ),
  'getCommentListIds' : IDL.Func([], [IDL.Vec(CommentListId)], ['query']),
  'getCommentListTotal' : IDL.Func(
      [IDL.Text, CommentListId],
      [IDL.Nat],
      ['query'],
    ),
  'getMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getRemainingCount' : IDL.Func([CommentListId], [IDL.Nat], ['query']),
  'getUserCommentHistory' : IDL.Func(
      [DeviceId],
      [IDL.Vec(IDL.Tuple(CommentListId, IDL.Bool))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func([Principal], [IDL.Opt(UserProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeAllRatingImages' : IDL.Func([IDL.Text], [], []),
  'removeComment' : IDL.Func([IDL.Text, CommentListId, CommentId], [], []),
  'removeRatingImage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'replyMessage' : IDL.Func([IDL.Text, IDL.Text], [MessageId], []),
  'resetBulkGeneratorKey' : IDL.Func([IDL.Text], [], []),
  'resetCommentList' : IDL.Func([IDL.Text, CommentListId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Text], [MessageId], []),
  'setBulkGeneratorKey' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'uploadRatingImage' : IDL.Func([ExternalBlob], [RatingImageId], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const CommentListId = IDL.Text;
  const CommentId = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Comment = IDL.Record({
    'id' : CommentId,
    'content' : IDL.Text,
    'used' : IDL.Bool,
    'timestamp' : Time,
  });
  const DeviceId = IDL.Text;
  const MessageId = IDL.Text;
  const MessageSide = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
  const Message = IDL.Record({
    'id' : MessageId,
    'content' : IDL.Text,
    'side' : MessageSide,
    'isRead' : IDL.Bool,
    'timestamp' : Time,
  });
  const RatingImageId = IDL.Text;
  const Principal = IDL.Principal;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const RatingImageMetadata = IDL.Record({
    'id' : RatingImageId,
    'timestamp' : Time,
    'uploader' : Principal,
    'image' : ExternalBlob,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([CommentListId, CommentId, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearAllCommentLists' : IDL.Func([IDL.Text], [], []),
    'createCommentList' : IDL.Func([IDL.Text, CommentListId], [], []),
    'deleteCommentList' : IDL.Func([IDL.Text, CommentListId], [], []),
    'generateBulkComments' : IDL.Func(
        [IDL.Text, CommentListId, IDL.Nat],
        [IDL.Vec(Comment)],
        [],
      ),
    'generateComment' : IDL.Func(
        [CommentListId, DeviceId],
        [IDL.Opt(Comment)],
        [],
      ),
    'getAllBulkCommentTotals' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(CommentListId, IDL.Nat))],
        ['query'],
      ),
    'getAllMessages' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
    'getAllRatingImages' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(RatingImageMetadata)],
        ['query'],
      ),
    'getAvailableComments' : IDL.Func(
        [CommentListId],
        [IDL.Opt(IDL.Vec(Comment))],
        ['query'],
      ),
    'getBulkGeneratorKey' : IDL.Func(
        [IDL.Text, IDL.Bool],
        [IDL.Opt(IDL.Text)],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommentList' : IDL.Func(
        [IDL.Text, CommentListId],
        [IDL.Vec(Comment)],
        ['query'],
      ),
    'getCommentListIds' : IDL.Func([], [IDL.Vec(CommentListId)], ['query']),
    'getCommentListTotal' : IDL.Func(
        [IDL.Text, CommentListId],
        [IDL.Nat],
        ['query'],
      ),
    'getMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getRemainingCount' : IDL.Func([CommentListId], [IDL.Nat], ['query']),
    'getUserCommentHistory' : IDL.Func(
        [DeviceId],
        [IDL.Vec(IDL.Tuple(CommentListId, IDL.Bool))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func([Principal], [IDL.Opt(UserProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeAllRatingImages' : IDL.Func([IDL.Text], [], []),
    'removeComment' : IDL.Func([IDL.Text, CommentListId, CommentId], [], []),
    'removeRatingImage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'replyMessage' : IDL.Func([IDL.Text, IDL.Text], [MessageId], []),
    'resetBulkGeneratorKey' : IDL.Func([IDL.Text], [], []),
    'resetCommentList' : IDL.Func([IDL.Text, CommentListId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Text], [MessageId], []),
    'setBulkGeneratorKey' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'uploadRatingImage' : IDL.Func([ExternalBlob], [RatingImageId], []),
  });
};

export const init = ({ IDL }) => { return []; };