/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const CommentListId = IDL.Text;
export const CommentId = IDL.Text;
export const Principal = IDL.Principal;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RatingImageId = IDL.Text;
export const Time = IDL.Int;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const RatingImageMetadata = IDL.Record({
  'id' : RatingImageId,
  'userName' : IDL.Text,
  'timestamp' : Time,
  'uploader' : Principal,
  'image' : ExternalBlob,
});
export const Comment = IDL.Record({
  'id' : CommentId,
  'content' : IDL.Text,
  'used' : IDL.Bool,
  'timestamp' : Time,
});
export const MessageId = IDL.Text;
export const MessageSide = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
});
export const Message = IDL.Record({
  'id' : MessageId,
  'content' : IDL.Text,
  'side' : MessageSide,
  'isRead' : IDL.Bool,
  'timestamp' : Time,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const PaymentRecord = IDL.Record({
  'id' : IDL.Text,
  'status' : PaymentStatus,
  'userPrincipal' : Principal,
  'timestamp' : Time,
  'amount' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'upiDetails' : IDL.Text,
  'name' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func(
      [IDL.Text, CommentListId, CommentId, IDL.Text],
      [],
      [],
    ),
  'addFundsToWallet' : IDL.Func([IDL.Text, Principal, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearAllCommentLists' : IDL.Func([IDL.Text], [], []),
  'createCommentList' : IDL.Func([IDL.Text, CommentListId], [], []),
  'deleteCommentList' : IDL.Func([IDL.Text, CommentListId], [], []),
  'downloadAllRatingImages' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(RatingImageMetadata)],
      ['query'],
    ),
  'generateBulkComments' : IDL.Func(
      [IDL.Text, CommentListId, IDL.Nat],
      [IDL.Vec(Comment)],
      [],
    ),
  'getAllBulkCommentTotals' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(CommentListId, IDL.Nat))],
      ['query'],
    ),
  'getAllMessages' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
  'getAllPaymentRecords' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(Principal, IDL.Vec(PaymentRecord)))],
      ['query'],
    ),
  'getAllUserRatingImages' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(RatingImageMetadata)))],
      ['query'],
    ),
  'getAvailableComments' : IDL.Func(
      [CommentListId],
      [IDL.Opt(IDL.Vec(Comment))],
      ['query'],
    ),
  'getBulkGeneratorKey' : IDL.Func(
      [IDL.Text, IDL.Bool],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommentList' : IDL.Func(
      [IDL.Text, CommentListId],
      [IDL.Vec(Comment)],
      ['query'],
    ),
  'getCommentListIds' : IDL.Func([], [IDL.Vec(CommentListId)], ['query']),
  'getCommentListTotal' : IDL.Func(
      [IDL.Text, CommentListId],
      [IDL.Nat],
      ['query'],
    ),
  'getLockedCommentListIds' : IDL.Func([], [IDL.Vec(CommentListId)], ['query']),
  'getLockedCommentListsTotal' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getPaymentHistory' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
  'getRemainingCount' : IDL.Func([CommentListId], [IDL.Nat], ['query']),
  'getTotalUserRatingCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func([Principal], [IDL.Opt(UserProfile)], ['query']),
  'getUserRatingImageCount' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Nat],
      ['query'],
    ),
  'getWalletBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCommentListLocked' : IDL.Func([CommentListId], [IDL.Bool], ['query']),
  'lockCommentList' : IDL.Func([IDL.Text, CommentListId], [], []),
  'removeAllUserRatingImages' : IDL.Func([IDL.Text], [], []),
  'removeComment' : IDL.Func([IDL.Text, CommentListId, CommentId], [], []),
  'removeRatingImage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'replyMessage' : IDL.Func([IDL.Text, IDL.Text], [MessageId], []),
  'resetBulkGeneratorKey' : IDL.Func([IDL.Text], [], []),
  'resetCommentList' : IDL.Func([IDL.Text, CommentListId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Text], [MessageId], []),
  'setBulkGeneratorKey' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'unlockCommentList' : IDL.Func([IDL.Text, CommentListId], [], []),
  'updatePaymentStatus' : IDL.Func(
      [IDL.Text, Principal, IDL.Text, PaymentStatus],
      [],
      [],
    ),
  'uploadRatingImage' : IDL.Func(
      [IDL.Text, IDL.Text, ExternalBlob],
      [RatingImageId],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const CommentListId = IDL.Text;
  const CommentId = IDL.Text;
  const Principal = IDL.Principal;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RatingImageId = IDL.Text;
  const Time = IDL.Int;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const RatingImageMetadata = IDL.Record({
    'id' : RatingImageId,
    'userName' : IDL.Text,
    'timestamp' : Time,
    'uploader' : Principal,
    'image' : ExternalBlob,
  });
  const Comment = IDL.Record({
    'id' : CommentId,
    'content' : IDL.Text,
    'used' : IDL.Bool,
    'timestamp' : Time,
  });
  const MessageId = IDL.Text;
  const MessageSide = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
  const Message = IDL.Record({
    'id' : MessageId,
    'content' : IDL.Text,
    'side' : MessageSide,
    'isRead' : IDL.Bool,
    'timestamp' : Time,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const PaymentRecord = IDL.Record({
    'id' : IDL.Text,
    'status' : PaymentStatus,
    'userPrincipal' : Principal,
    'timestamp' : Time,
    'amount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'upiDetails' : IDL.Text,
    'name' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'email' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func(
        [IDL.Text, CommentListId, CommentId, IDL.Text],
        [],
        [],
      ),
    'addFundsToWallet' : IDL.Func([IDL.Text, Principal, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearAllCommentLists' : IDL.Func([IDL.Text], [], []),
    'createCommentList' : IDL.Func([IDL.Text, CommentListId], [], []),
    'deleteCommentList' : IDL.Func([IDL.Text, CommentListId], [], []),
    'downloadAllRatingImages' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(RatingImageMetadata)],
        ['query'],
      ),
    'generateBulkComments' : IDL.Func(
        [IDL.Text, CommentListId, IDL.Nat],
        [IDL.Vec(Comment)],
        [],
      ),
    'getAllBulkCommentTotals' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(CommentListId, IDL.Nat))],
        ['query'],
      ),
    'getAllMessages' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
    'getAllPaymentRecords' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(Principal, IDL.Vec(PaymentRecord)))],
        ['query'],
      ),
    'getAllUserRatingImages' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(RatingImageMetadata)))],
        ['query'],
      ),
    'getAvailableComments' : IDL.Func(
        [CommentListId],
        [IDL.Opt(IDL.Vec(Comment))],
        ['query'],
      ),
    'getBulkGeneratorKey' : IDL.Func(
        [IDL.Text, IDL.Bool],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommentList' : IDL.Func(
        [IDL.Text, CommentListId],
        [IDL.Vec(Comment)],
        ['query'],
      ),
    'getCommentListIds' : IDL.Func([], [IDL.Vec(CommentListId)], ['query']),
    'getCommentListTotal' : IDL.Func(
        [IDL.Text, CommentListId],
        [IDL.Nat],
        ['query'],
      ),
    'getLockedCommentListIds' : IDL.Func(
        [],
        [IDL.Vec(CommentListId)],
        ['query'],
      ),
    'getLockedCommentListsTotal' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getPaymentHistory' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
    'getRemainingCount' : IDL.Func([CommentListId], [IDL.Nat], ['query']),
    'getTotalUserRatingCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func([Principal], [IDL.Opt(UserProfile)], ['query']),
    'getUserRatingImageCount' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Nat],
        ['query'],
      ),
    'getWalletBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCommentListLocked' : IDL.Func([CommentListId], [IDL.Bool], ['query']),
    'lockCommentList' : IDL.Func([IDL.Text, CommentListId], [], []),
    'removeAllUserRatingImages' : IDL.Func([IDL.Text], [], []),
    'removeComment' : IDL.Func([IDL.Text, CommentListId, CommentId], [], []),
    'removeRatingImage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'replyMessage' : IDL.Func([IDL.Text, IDL.Text], [MessageId], []),
    'resetBulkGeneratorKey' : IDL.Func([IDL.Text], [], []),
    'resetCommentList' : IDL.Func([IDL.Text, CommentListId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Text], [MessageId], []),
    'setBulkGeneratorKey' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'unlockCommentList' : IDL.Func([IDL.Text, CommentListId], [], []),
    'updatePaymentStatus' : IDL.Func(
        [IDL.Text, Principal, IDL.Text, PaymentStatus],
        [],
        [],
      ),
    'uploadRatingImage' : IDL.Func(
        [IDL.Text, IDL.Text, ExternalBlob],
        [RatingImageId],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };