/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'id' : CommentId,
  'content' : string,
  'used' : boolean,
  'timestamp' : Time,
}
export type CommentId = string;
export type CommentListId = string;
export type DeviceId = string;
export type ExternalBlob = Uint8Array;
export interface Message {
  'id' : MessageId,
  'content' : string,
  'side' : MessageSide,
  'isRead' : boolean,
  'timestamp' : Time,
}
export type MessageId = string;
export type MessageSide = { 'admin' : null } |
  { 'user' : null };
export type Principal = Principal;
export type RatingImageId = string;
export interface RatingImageMetadata {
  'id' : RatingImageId,
  'timestamp' : Time,
  'uploader' : Principal,
  'image' : ExternalBlob,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[CommentListId, CommentId, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearAllCommentLists' : ActorMethod<[string], undefined>,
  'createCommentList' : ActorMethod<[string, CommentListId], undefined>,
  'deleteCommentList' : ActorMethod<[string, CommentListId], undefined>,
  'generateBulkComments' : ActorMethod<
    [string, CommentListId, bigint],
    Array<Comment>
  >,
  'generateComment' : ActorMethod<[CommentListId, DeviceId], [] | [Comment]>,
  'getAllBulkCommentTotals' : ActorMethod<
    [string],
    Array<[CommentListId, bigint]>
  >,
  'getAllMessages' : ActorMethod<[string], Array<Message>>,
  'getAllRatingImages' : ActorMethod<[string], Array<RatingImageMetadata>>,
  'getAvailableComments' : ActorMethod<[CommentListId], [] | [Array<Comment>]>,
  'getBulkGeneratorKey' : ActorMethod<[string, boolean], [] | [string]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommentList' : ActorMethod<[string, CommentListId], Array<Comment>>,
  'getCommentListIds' : ActorMethod<[], Array<CommentListId>>,
  'getCommentListTotal' : ActorMethod<[string, CommentListId], bigint>,
  'getMessages' : ActorMethod<[], Array<Message>>,
  'getRemainingCount' : ActorMethod<[CommentListId], bigint>,
  'getUserCommentHistory' : ActorMethod<
    [DeviceId],
    Array<[CommentListId, boolean]>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeAllRatingImages' : ActorMethod<[string], undefined>,
  'removeComment' : ActorMethod<[string, CommentListId, CommentId], undefined>,
  'removeRatingImage' : ActorMethod<[string, string], undefined>,
  'replyMessage' : ActorMethod<[string, string], MessageId>,
  'resetBulkGeneratorKey' : ActorMethod<[string], undefined>,
  'resetCommentList' : ActorMethod<[string, CommentListId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[string], MessageId>,
  'setBulkGeneratorKey' : ActorMethod<[string, string], undefined>,
  'uploadRatingImage' : ActorMethod<[ExternalBlob], RatingImageId>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];