/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AccessCode = IDL.Text;
export const BulkKey = IDL.Text;
export const AccessKey = IDL.Record({
  'key' : IDL.Text,
  'description' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Comment = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'used' : IDL.Bool,
  'isAdminComment' : IDL.Bool,
});
export const Time = IDL.Int;
export const Principal = IDL.Principal;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const RatingImage = IDL.Record({
  'id' : IDL.Text,
  'userName' : IDL.Text,
  'timestamp' : Time,
  'uploader' : Principal,
  'image' : ExternalBlob,
});
export const LiveRatingListEntry = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Bool,
  'name' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBulkComments' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'addLiveRatingListEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkLiveNameExists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'createAccessKey' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createAdminAccessCode' : IDL.Func([], [AccessCode], []),
  'deleteAccessKey' : IDL.Func([IDL.Text], [], []),
  'deleteLiveRatingListEntry' : IDL.Func([IDL.Text], [], []),
  'generateAdminOnlyComments' : IDL.Func([IDL.Text, IDL.Bool], [IDL.Bool], []),
  'generateAiComments' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      [],
    ),
  'generateBulkAccessKeys' : IDL.Func([IDL.Nat], [IDL.Vec(BulkKey)], []),
  'generateUserComments' : IDL.Func([IDL.Vec(IDL.Text)], [IDL.Bool], []),
  'getAccessCodesForAdmin' : IDL.Func([], [IDL.Vec(AccessCode)], []),
  'getAccessKeys' : IDL.Func([], [IDL.Vec(AccessKey)], ['query']),
  'getAllKeys' : IDL.Func(
      [],
      [
        IDL.Record({
          'adminAccessCodes' : IDL.Vec(AccessCode),
          'bulkKeysActive' : IDL.Vec(BulkKey),
          'bulkKeysDisabled' : IDL.Vec(BulkKey),
        }),
      ],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommentStats' : IDL.Func([], [IDL.Nat, IDL.Nat, IDL.Nat], ['query']),
  'getComments' : IDL.Func([], [IDL.Vec(Comment)], ['query']),
  'getImages' : IDL.Func([], [IDL.Vec(RatingImage)], ['query']),
  'getLiveRatingListEntries' : IDL.Func(
      [],
      [IDL.Vec(LiveRatingListEntry)],
      ['query'],
    ),
  'getNextUnusedComment' : IDL.Func([], [Comment], []),
  'getOtherComments' : IDL.Func([], [IDL.Vec(Comment)], ['query']),
  'getUserProfile' : IDL.Func([Principal], [IDL.Opt(UserProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateAccessKey' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateLiveRatingListEntryStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'uploadImage' : IDL.Func([ExternalBlob], [IDL.Bool], []),
  'useAdminAccessCode' : IDL.Func([AccessCode], [IDL.Bool], []),
  'useBulkAccessKey' : IDL.Func([BulkKey], [IDL.Bool], []),
  'validateAccessKey' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AccessCode = IDL.Text;
  const BulkKey = IDL.Text;
  const AccessKey = IDL.Record({ 'key' : IDL.Text, 'description' : IDL.Text });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Comment = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'used' : IDL.Bool,
    'isAdminComment' : IDL.Bool,
  });
  const Time = IDL.Int;
  const Principal = IDL.Principal;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const RatingImage = IDL.Record({
    'id' : IDL.Text,
    'userName' : IDL.Text,
    'timestamp' : Time,
    'uploader' : Principal,
    'image' : ExternalBlob,
  });
  const LiveRatingListEntry = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Bool,
    'name' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBulkComments' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'addLiveRatingListEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkLiveNameExists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'createAccessKey' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createAdminAccessCode' : IDL.Func([], [AccessCode], []),
    'deleteAccessKey' : IDL.Func([IDL.Text], [], []),
    'deleteLiveRatingListEntry' : IDL.Func([IDL.Text], [], []),
    'generateAdminOnlyComments' : IDL.Func(
        [IDL.Text, IDL.Bool],
        [IDL.Bool],
        [],
      ),
    'generateAiComments' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        [],
      ),
    'generateBulkAccessKeys' : IDL.Func([IDL.Nat], [IDL.Vec(BulkKey)], []),
    'generateUserComments' : IDL.Func([IDL.Vec(IDL.Text)], [IDL.Bool], []),
    'getAccessCodesForAdmin' : IDL.Func([], [IDL.Vec(AccessCode)], []),
    'getAccessKeys' : IDL.Func([], [IDL.Vec(AccessKey)], ['query']),
    'getAllKeys' : IDL.Func(
        [],
        [
          IDL.Record({
            'adminAccessCodes' : IDL.Vec(AccessCode),
            'bulkKeysActive' : IDL.Vec(BulkKey),
            'bulkKeysDisabled' : IDL.Vec(BulkKey),
          }),
        ],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommentStats' : IDL.Func([], [IDL.Nat, IDL.Nat, IDL.Nat], ['query']),
    'getComments' : IDL.Func([], [IDL.Vec(Comment)], ['query']),
    'getImages' : IDL.Func([], [IDL.Vec(RatingImage)], ['query']),
    'getLiveRatingListEntries' : IDL.Func(
        [],
        [IDL.Vec(LiveRatingListEntry)],
        ['query'],
      ),
    'getNextUnusedComment' : IDL.Func([], [Comment], []),
    'getOtherComments' : IDL.Func([], [IDL.Vec(Comment)], ['query']),
    'getUserProfile' : IDL.Func([Principal], [IDL.Opt(UserProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateAccessKey' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateLiveRatingListEntryStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'uploadImage' : IDL.Func([ExternalBlob], [IDL.Bool], []),
    'useAdminAccessCode' : IDL.Func([AccessCode], [IDL.Bool], []),
    'useBulkAccessKey' : IDL.Func([BulkKey], [IDL.Bool], []),
    'validateAccessKey' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };