/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AccessCode = string;
export interface AccessKey { 'key' : string, 'description' : string }
export type BulkKey = string;
export interface Comment {
  'id' : string,
  'content' : string,
  'used' : boolean,
  'isAdminComment' : boolean,
}
export type ExternalBlob = Uint8Array;
export interface LiveRatingListEntry {
  'id' : string,
  'status' : boolean,
  'name' : string,
}
export type Principal = Principal;
export interface RatingImage {
  'id' : string,
  'userName' : string,
  'timestamp' : Time,
  'uploader' : Principal,
  'image' : ExternalBlob,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBulkComments' : ActorMethod<[Array<string>], undefined>,
  'addLiveRatingListEntry' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkLiveNameExists' : ActorMethod<[string], boolean>,
  'createAccessKey' : ActorMethod<[string, string], undefined>,
  'createAdminAccessCode' : ActorMethod<[], AccessCode>,
  'deleteAccessKey' : ActorMethod<[string], undefined>,
  'deleteLiveRatingListEntry' : ActorMethod<[string], undefined>,
  'generateAdminOnlyComments' : ActorMethod<[string, boolean], boolean>,
  'generateAiComments' : ActorMethod<[bigint, bigint], Array<[string, string]>>,
  'generateBulkAccessKeys' : ActorMethod<[bigint], Array<BulkKey>>,
  'generateUserComments' : ActorMethod<[Array<string>], boolean>,
  'getAccessCodesForAdmin' : ActorMethod<[], Array<AccessCode>>,
  'getAccessKeys' : ActorMethod<[], Array<AccessKey>>,
  'getAllKeys' : ActorMethod<
    [],
    {
      'adminAccessCodes' : Array<AccessCode>,
      'bulkKeysActive' : Array<BulkKey>,
      'bulkKeysDisabled' : Array<BulkKey>,
    }
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommentStats' : ActorMethod<[], [bigint, bigint, bigint]>,
  'getComments' : ActorMethod<[], Array<Comment>>,
  'getImages' : ActorMethod<[], Array<RatingImage>>,
  'getLiveRatingListEntries' : ActorMethod<[], Array<LiveRatingListEntry>>,
  'getNextUnusedComment' : ActorMethod<[], Comment>,
  'getOtherComments' : ActorMethod<[], Array<Comment>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateAccessKey' : ActorMethod<[string, string, string], undefined>,
  'updateLiveRatingListEntryStatus' : ActorMethod<[string, boolean], undefined>,
  'uploadImage' : ActorMethod<[ExternalBlob], boolean>,
  'useAdminAccessCode' : ActorMethod<[AccessCode], boolean>,
  'useBulkAccessKey' : ActorMethod<[BulkKey], boolean>,
  'validateAccessKey' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];